kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-foto-show
  namespace: sam-sam-showcase
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
  storageClassName: rook-cephfs
  volumeMode: Filesystem
