apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: group-7-felix
  labels:
    app: user-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/q/metrics"
    prometheus.io/port: "18181"
spec:
  selector:
    app: user-service
  ports:
    - name: http
      port: 80
      targetPort: 18181
