apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: user-service-metrics
  namespace: group-7-development
  labels:
    release: prometheus
    app.kubernetes.io/instance: enbition
    application: user-service
spec:
  selector:
    matchLabels:
      app: user-service
  endpoints:
    - port: http
      path: /q/metrics
      interval: 15s
